# Generated by Django 5.2.6 on 2025-09-09 12:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('device', models.CharField(blank=True, max_length=255)),
                ('browser', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(blank=True, max_length=255)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National Card'), ('drivers_license', "Driver's License")], default='passport', max_length=50)),
                ('passport_file', models.FileField(blank=True, null=True, upload_to='kyc/passport/')),
                ('id_front_file', models.FileField(blank=True, null=True, upload_to='kyc/id_front/')),
                ('id_back_file', models.FileField(blank=True, null=True, upload_to='kyc/id_back/')),
                ('drivers_file', models.FileField(blank=True, null=True, upload_to='kyc/drivers/')),
                ('wallet_address', models.CharField(blank=True, max_length=255)),
                ('wallet_type', models.CharField(blank=True, max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('not_submitted', 'Not submitted'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('incomplete', 'Incomplete')], default='pending', max_length=40)),
                ('admin_note', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('surname', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('zip_code', models.CharField(blank=True, max_length=30)),
                ('telegram', models.CharField(blank=True, max_length=100)),
                ('wallet_address', models.CharField(blank=True, max_length=250)),
                ('wallet_type', models.CharField(blank=True, max_length=50)),
                ('notify_resume_sales', models.BooleanField(default=False)),
                ('notify_latest_news', models.BooleanField(default=True)),
                ('notify_unusual_activity', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_ref', models.CharField(blank=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=16)),
                ('description', models.TextField(blank=True)),
                ('tx_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
