# Generated by Django 5.2.6 on 2025-11-17 23:57

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_cardrequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='masked_pan',
        ),
        migrations.AddField(
            model_name='card',
            name='card_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
