# Generated by Django 5.2.6 on 2025-11-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_userprofile_options_remove_kyc_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='kyc_doc',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
