# Generated by Django 5.2.6 on 2025-11-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_kyc_kyc_doc_alter_kyc_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
