# Generated by Django 5.2.6 on 2025-11-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_kyc_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='reference',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
